import axios from 'axios';
import { Move, PokeapiResponse } from '../interfaces/pokeapi-response.interface';


export class Pokemon {

  // public id: number;
  // public name: string;
  get imageUrl(): string {
    return `https://pokemon.com/${ this.id }.jpg`;
  }

  constructor(
    public readonly id: number,
    public name: string,
    // public imageUrl: string,
  ) {
    // this.id = id;
    // this.name = name;// Generated by https://quicktype.io


    // console.log('constructor llamado');
  }

  scream() {
    console.log(`${ this.name.toUpperCase() }!!!`);
    // this.speak();
  }

  speak() {
    console.log(`${ this.name }!, ${ this.name }`);
  }

  async getMoves(): Promise<Move[]> {
    // const moves = 10;
    const { data } = await axios.get<PokeapiResponse>('https://pokeapi.co/api/v2/pokemon/4')

    return data.moves;
  }
}

export const charmander = new Pokemon(2, 'Charmander');
// charmander.id = 10
// charmander.name = 'Mew'
console.log(charmander.imageUrl);

charmander.scream();
// charmander.speak();
console.log(await charmander.getMoves());